baseURL = "http://dhritishikhar.com/"
languageCode = "en-us"
title = "Dhriti Shikhar"
theme = "elephants"
contentDir = "content"
publishDir = "docs"


[params]
	author = "Dhriti Shikhar"
	sitename = "Dhriti Shikhar"
